---
- name: Update Repositorios
  apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    force_apt_get: true
  become: true

- name: Instalando pacotes essenciais
  apt: 
    name: "{{ pacotes }}"
    state: latest
  become: true

- name: GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: Docker python
  pip:
    name: docker
  become: true

- name: Install Docker
  apt:
    name: "{{ docker }}"
    state: latest
    update_cache: yes
  become: true
